import { execFileSync } from 'child_process';
import type { IPythonPathResolverConfig } from './PathResolver';
import {
  normalizeSourceRoot,
  parseSourceRootsFromRaw,
  sanitizeSourceRoots,
} from './projectConfigParser';

const SOURCE_ROOT_DISCOVERY_SCRIPT_BASE64 =
  'aW1wb3J0IGNvbmZpZ3BhcnNlcgppbXBvcnQganNvbgppbXBvcnQgcGF0aGxpYgppbXBvcnQgcmUKaW1wb3J0IHN5cwoKd29ya3NwYWNlX3Jvb3QgPSBwYXRobGliLlBhdGgoc3lzLmFyZ3ZbMV0pCnNvdXJjZV9yb290cyA9IFtdCgpkZWYgYWRkX3NvdXJjZV9yb290KHJhd192YWx1ZSk6CiAgICBpZiBub3QgaXNpbnN0YW5jZShyYXdfdmFsdWUsIHN0cik6CiAgICAgICAgcmV0dXJuCgogICAgbm9ybWFsaXplZCA9IHJhd192YWx1ZS5zdHJpcCgpLnN0cmlwKCciJykuc3RyaXAoIiciKS5yZXBsYWNlKCJcXCIsICIvIikucnN0cmlwKCIvIikKICAgIGlmIG5vdCBub3JtYWxpemVkIG9yIG5vcm1hbGl6ZWQgPT0gIi4iOgogICAgICAgIHJldHVybgoKICAgIGlmIG5vcm1hbGl6ZWQgbm90IGluIHNvdXJjZV9yb290czoKICAgICAgICBzb3VyY2Vfcm9vdHMuYXBwZW5kKG5vcm1hbGl6ZWQpCgpkZWYgcGFyc2VfcHlwcm9qZWN0KGNvbnRlbnQpOgogICAgZm9yIHdoZXJlX2xpc3QgaW4gcmUuZmluZGl0ZXIociJcYndoZXJlXHMqPVxzKlxbKFteXF1dKilcXSIsIGNvbnRlbnQpOgogICAgICAgIGZvciB3aGVyZV9pdGVtIGluIHJlLmZpbmRpdGVyKHIiWydcIl0oW14nXCJdKylbJ1wiXSIsIHdoZXJlX2xpc3QuZ3JvdXAoMSkpOgogICAgICAgICAgICBhZGRfc291cmNlX3Jvb3Qod2hlcmVfaXRlbS5ncm91cCgxKSkKCiAgICBmb3Igd2hlcmVfc2luZ2xlIGluIHJlLmZpbmRpdGVyKHIiXGJ3aGVyZVxzKj1ccypbJ1wiXShbXidcIl0rKVsnXCJdIiwgY29udGVudCk6CiAgICAgICAgYWRkX3NvdXJjZV9yb290KHdoZXJlX3NpbmdsZS5ncm91cCgxKSkKCiAgICBmb3IgZnJvbV92YWx1ZSBpbiByZS5maW5kaXRlcihyIlxiZnJvbVxzKj1ccypbJ1wiXShbXidcIl0rKVsnXCJdIiwgY29udGVudCk6CiAgICAgICAgYWRkX3NvdXJjZV9yb290KGZyb21fdmFsdWUuZ3JvdXAoMSkpCgogICAgZm9yIHBhY2thZ2VfZGlyX2Jsb2NrIGluIHJlLmZpbmRpdGVyKHIiXGJwYWNrYWdlLWRpclxzKj1ccypceyhbXn1dKilcfSIsIGNvbnRlbnQsIGZsYWdzPXJlLlMpOgogICAgICAgIGZvciBlbnRyeSBpbiBwYWNrYWdlX2Rpcl9ibG9jay5ncm91cCgxKS5zcGxpdCgiLCIpOgogICAgICAgICAgICBtYXRjaCA9IHJlLm1hdGNoKHIiXlxzKlsnXCJdPyhbXidcIl0qKVsnXCJdP1xzKj1ccypbJ1wiXShbXidcIl0rKVsnXCJdXHMqJCIsIGVudHJ5KQogICAgICAgICAgICBpZiBub3QgbWF0Y2g6CiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICBpZiBtYXRjaC5ncm91cCgxKS5zdHJpcCgpOgogICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgYWRkX3NvdXJjZV9yb290KG1hdGNoLmdyb3VwKDIpKQoKZGVmIHBhcnNlX3NldHVwX2NmZyhjb250ZW50KToKICAgIHBhcnNlciA9IGNvbmZpZ3BhcnNlci5Db25maWdQYXJzZXIoaW50ZXJwb2xhdGlvbj1Ob25lKQogICAgcGFyc2VyLnJlYWRfc3RyaW5nKGNvbnRlbnQpCgogICAgaWYgcGFyc2VyLmhhc19vcHRpb24oIm9wdGlvbnMucGFja2FnZXMuZmluZCIsICJ3aGVyZSIpOgogICAgICAgIHdoZXJlX3ZhbHVlID0gcGFyc2VyLmdldCgib3B0aW9ucy5wYWNrYWdlcy5maW5kIiwgIndoZXJlIikKICAgICAgICBmb3IgY2FuZGlkYXRlIGluIHJlLnNwbGl0KHIiXHI/XG58LCIsIHdoZXJlX3ZhbHVlKToKICAgICAgICAgICAgYWRkX3NvdXJjZV9yb290KGNhbmRpZGF0ZSkKCiAgICBpZiBwYXJzZXIuaGFzX29wdGlvbigib3B0aW9ucyIsICJwYWNrYWdlX2RpciIpOgogICAgICAgIHBhY2thZ2VfZGlyX3ZhbHVlID0gcGFyc2VyLmdldCgib3B0aW9ucyIsICJwYWNrYWdlX2RpciIpCiAgICAgICAgZm9yIHJhd19saW5lIGluIHBhY2thZ2VfZGlyX3ZhbHVlLnNwbGl0bGluZXMoKToKICAgICAgICAgICAgbGluZSA9IHJhd19saW5lLnN0cmlwKCkKICAgICAgICAgICAgaWYgbm90IGxpbmUgb3IgbGluZS5zdGFydHN3aXRoKCIjIikgb3IgbGluZS5zdGFydHN3aXRoKCI7Iik6CiAgICAgICAgICAgICAgICBjb250aW51ZQoKICAgICAgICAgICAgaWYgbGluZS5zdGFydHN3aXRoKCI9Iik6CiAgICAgICAgICAgICAgICBhZGRfc291cmNlX3Jvb3QobGluZVsxOl0pCiAgICAgICAgICAgICAgICBjb250aW51ZQoKICAgICAgICAgICAgbWF0Y2ggPSByZS5tYXRjaChyIl5bJ1wiXT8oW14nXCJdKilbJ1wiXT9ccyo9XHMqKC4rKSQiLCBsaW5lKQogICAgICAgICAgICBpZiBub3QgbWF0Y2g6CiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICBpZiBtYXRjaC5ncm91cCgxKS5zdHJpcCgpOgogICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgYWRkX3NvdXJjZV9yb290KG1hdGNoLmdyb3VwKDIpKQoKcHlwcm9qZWN0X3BhdGggPSB3b3Jrc3BhY2Vfcm9vdCAvICJweXByb2plY3QudG9tbCIKaWYgcHlwcm9qZWN0X3BhdGguZXhpc3RzKCk6CiAgICB0cnk6CiAgICAgICAgcGFyc2VfcHlwcm9qZWN0KHB5cHJvamVjdF9wYXRoLnJlYWRfdGV4dChlbmNvZGluZz0idXRmLTgiKSkKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgcGFzcwoKc2V0dXBfY2ZnX3BhdGggPSB3b3Jrc3BhY2Vfcm9vdCAvICJzZXR1cC5jZmciCmlmIHNldHVwX2NmZ19wYXRoLmV4aXN0cygpOgogICAgdHJ5OgogICAgICAgIHBhcnNlX3NldHVwX2NmZyhzZXR1cF9jZmdfcGF0aC5yZWFkX3RleHQoZW5jb2Rpbmc9InV0Zi04IikpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHBhc3MKCnByaW50KGpzb24uZHVtcHMoc291cmNlX3Jvb3RzKSkK';

const PYTHON_SOURCE_ROOT_DISCOVERY_SCRIPT = Buffer.from(
  SOURCE_ROOT_DISCOVERY_SCRIPT_BASE64,
  'base64',
).toString('utf8');
const SOURCE_ROOT_PARSE_BUFFER_BYTES = 1024 * 1024 * 5;

/**
 * Loads Python project configuration from packaging metadata files.
 * Supports pyproject.toml and setup.cfg source-root discovery.
 */
export async function loadPythonConfig(workspaceRoot: string): Promise<IPythonPathResolverConfig> {
  try {
    const raw = execFileSync('python3', ['-c', PYTHON_SOURCE_ROOT_DISCOVERY_SCRIPT, workspaceRoot], {
      maxBuffer: SOURCE_ROOT_PARSE_BUFFER_BYTES,
    });

    return {
      sourceRoots: parseSourceRootsFromRaw(raw.toString('utf8')),
      resolveInitFiles: true,
    };
  } catch (error) {
    console.warn('[CodeGraphy] Failed to parse python project config:', error);
    return {
      sourceRoots: [],
      resolveInitFiles: true,
    };
  }
}

export const __test = {
  parseSourceRootsFromRaw,
  sanitizeSourceRoots,
  normalizeSourceRoot,
  PYTHON_SOURCE_ROOT_DISCOVERY_SCRIPT,
};
