import type { GraphStateFields } from './state';
import { DEFAULT_PHYSICS, DEFAULT_SEARCH_OPTIONS } from './defaults';
import { DEFAULT_DIRECTION_COLOR } from '../../shared/fileColors';

export const INITIAL_STATE: GraphStateFields = {
  graphData: null,
  graphHasIndex: false,
  graphIndexFreshness: 'missing' as const,
  graphIndexDetail: null,
  graphIsIndexing: false,
  graphIndexProgress: null,
  isLoading: true,
  searchQuery: '',
  searchOptions: DEFAULT_SEARCH_OPTIONS,
  favorites: new Set<string>(),
  bidirectionalMode: 'separate' as const,
  showOrphans: true,
  directionMode: 'arrows' as const,
  directionColor: DEFAULT_DIRECTION_COLOR,
  particleSpeed: 0.005,
  particleSize: 4,
  physicsPaused: false,
  showLabels: true,
  graphMode: '2d' as const,
  nodeSizeMode: 'connections' as const,
  physicsSettings: DEFAULT_PHYSICS,
  depthMode: false,
  depthLimit: 1,
  maxDepthLimit: 10,
  legends: [],
  optimisticLegendUpdates: {},
  optimisticUserLegends: null,
  filterPatterns: [],
  pluginFilterPatterns: [],
  pluginFilterGroups: [],
  disabledCustomFilterPatterns: [],
  disabledPluginFilterPatterns: [],
  dagMode: null,
  pluginStatuses: [],
  graphNodeTypes: [],
  graphEdgeTypes: [],
  nodeColors: {},
  nodeColorEnabled: {},
  nodeVisibility: {},
  edgeVisibility: {},
  nodeDecorations: {},
  edgeDecorations: {},
  pluginContextMenuItems: [],
  pluginExporters: [],
  pluginToolbarActions: [],
  expandedGroupId: null,
  activePanel: 'none' as const,
  maxFiles: 500,
  activeFilePath: null,
  timelineActive: false,
  timelineCommits: [],
  currentCommitSha: null,
  isIndexing: false,
  indexProgress: null,
  isPlaying: false,
  playbackSpeed: 1.0,
};
