import type { GraphStateFields } from './state';
import { DEFAULT_PHYSICS, DEFAULT_SEARCH_OPTIONS } from './defaults';
import { DEFAULT_DIRECTION_COLOR, DEFAULT_FOLDER_NODE_COLOR } from '../../shared/fileColors';

export const INITIAL_STATE: GraphStateFields = {
  graphData: null,
  isLoading: true,
  searchQuery: '',
  searchOptions: DEFAULT_SEARCH_OPTIONS,
  favorites: new Set<string>(),
  bidirectionalMode: 'separate' as const,
  showOrphans: true,
  directionMode: 'arrows' as const,
  directionColor: DEFAULT_DIRECTION_COLOR,
  particleSpeed: 0.005,
  particleSize: 4,
  showLabels: true,
  graphMode: '2d' as const,
  nodeSizeMode: 'connections' as const,
  physicsSettings: DEFAULT_PHYSICS,
  depthLimit: 1,
  groups: [],
  optimisticGroupUpdates: {},
  optimisticUserGroups: null,
  filterPatterns: [],
  pluginFilterPatterns: [],
  availableViews: [],
  activeViewId: 'codegraphy.connections',
  dagMode: null,
  folderNodeColor: DEFAULT_FOLDER_NODE_COLOR,
  pluginStatuses: [],
  nodeDecorations: {},
  edgeDecorations: {},
  pluginContextMenuItems: [],
  expandedGroupId: null,
  activePanel: 'none' as const,
  maxFiles: 500,
  timelineActive: false,
  timelineCommits: [],
  currentCommitSha: null,
  isIndexing: false,
  indexProgress: null,
  isPlaying: false,
  playbackSpeed: 1.0,
};
